#!/usr/bin/env ruby
require "readline"
require "jab"		# put jab.rb somewhere in your Ruby load path
			# ruby -e "puts $:"

begin
  Readline.vi_editing_mode
rescue NotImplementedError
  interject :info, "vi editing mode not available"
end

session = Jab.new
session.source "~/.jabrc", true
session.interact
